# Generated by Django 5.1.4 on 2025-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='2021-01-27', verbose_name='Дата публикации'),
        ),
    ]
